---
1.0.0alpha1:
  api: 1.0.0
  state:
    release: alpha
    api: alpha
  date: 2011-03-07
  license:
    identifier: LGPL-2.1
    uri: http://www.horde.org/licenses/lgpl21
  notes: |
    [jan] Mark PHP 7 as supported.
    [jan] Fix tests to work with PHPUnit 3.6.
