---
id: Kolab_Config
name: Kolab_Config
full: Kolab server configuration library
description: >
  This package reads the various Kolab server configuration files. It should
  also support retrieving configuration parameters from LDAP but this is not yet
  implemented.
list: dev
type: library
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.4
