---
id: Kolab_Config
name: Kolab_Config
full: Kolab server configuration library
description: >
  This package reads the various Kolab server configuration files. It should
  also support retrieving configuration parameters from LDAP but this is not yet
  implemented.
list: dev
type: library
